config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'memo' => 'daily_record#daily_record'
  get 'users/new'
  patch 'memo' => 'memos#update'
  resources :memo
  patch 'daily_record' => 'daily_record#update'
  resources :articles do
    resources :comments
  end
  root 'articles#index'
  get 'about' => 'articles#about'
  get 'daily_record' => 'daily_record#daily_record'
  get 'signup' => 'users#new'
  resources :users
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  post 'daily_record/next'
  post 'daily_record/previous'
  post 'daily_record/send_mail'
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validate :picture_size
  has_many :comments, dependent: :destroy
  
  mount_uploader :picture, PictureUploader
  
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "should be less than 5MB")
    end
  end
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :article
end

app/models/daily_record.rb
class DailyRecord < ActiveRecord::Base
  validates :date, uniqueness: true
end

app/models/memo.rb
class Memo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3 }, 
  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 1 }
    
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, only: [:create, :edit, :update, :new, :destroy]
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:success] = 'Article created successfully!'
      redirect_to @article
    else
      render 'new'
    end
  end
  
  def show
    @article = Article.find(params[:id])
    #debugger
  end
  
  def index
    @articles = Article.all.reverse
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = 'Article updated successfully!'
      redirect_to @article
    else
      render 'edit'
    end
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:success] = 'Article deleted successfully!'
    redirect_to articles_path
  end
  
  def about
  end
    
  private
  
  def article_params
    params.require(:article).permit(:title, :content, :picture)
  end
  
  def require_login
    if current_user == nil
      flash[:alert]='You need to login to do that!'
      redirect_to articles_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  
  private
    def comment_params
     params.require(:comment).permit(:content)
    end

end

app/controllers/daily_record_controller.rb
class DailyRecordController < ApplicationController
  before_action :require_login
  def daily_record
    @memo ||= Memo.create
    @memo = Memo.find_by(id:1)
    
    cookies[:base_date] ||= Time.now.at_midnight
    @base_date = cookies[:base_date].to_datetime
    @day1 = DailyRecord.find_by(date: @base_date)
    @day1 ||= DailyRecord.create(date: @base_date)
    
    @day2 = DailyRecord.find_by(date: @base_date + 1.day)
    @day2 ||= DailyRecord.create(date: @base_date + 1.day)
    
    @day3 = DailyRecord.find_by(date: @base_date + 2.day)
    @day3 ||= DailyRecord.create(date: @base_date + 2.day)
    
    @day4 = DailyRecord.find_by(date: @base_date + 3.day)
    @day4 ||= DailyRecord.create(date: @base_date + 3.day)
    
    @day5 = DailyRecord.find_by(date: @base_date + 4.day)
    @day5 ||= DailyRecord.create(date: @base_date + 4.day)
    
    @day6 = DailyRecord.find_by(date: @base_date + 5.day)
    @day6 ||= DailyRecord.create(date: @base_date + 5.day)
    
    @day7 = DailyRecord.find_by(date: @base_date + 6.day)
    @day7 ||= DailyRecord.create(date: @base_date + 6.day)
    
  end
  
  def update
    @daily_record = DailyRecord.find_by(date: params[:daily_record][:base_date].to_datetime)
    if @daily_record.update(daily_record_params)
      flash[:success] = "#{@daily_record.date.to_date} Updated successfully!!"
      redirect_to daily_record_path
    end
  end
  
  def next
    cookies[:base_date] = cookies[:base_date].to_datetime + 6.day
    redirect_to daily_record_path
  end
  
  def previous
    cookies[:base_date] = cookies[:base_date].to_datetime - 6.day
    redirect_to daily_record_path
  end
  
  def send_mail
    RecordMailer.send_records(params[:email]).deliver_now
    redirect_to daily_record_path
  end
  
  private
  def require_login
    if current_user.nil?
      redirect_to articles_path
      flash[:warning]='You need to login first!'
    end
  end
  
  def daily_record_params
    params.require(:daily_record).permit(:sleep_time, :restfulness, :study_progress)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def update
    d = Memo.first
    d.text = params[:memo][:text]
    d.save
    flash[:success]="Memo saved!"
    redirect_to daily_record_path
  end
  
  private
  
  def memo_params
    params.require(:memo).permit(:text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to articles_path
    else
      flash.now[:danger] = 'Invalid user name or password!'
      render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to articles_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "Sign up successfully!"
      log_in(@user)
      redirect_to articles_path
    else
      render 'new'
    end
  end
  
  
  private
  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/daily_record_helper.rb
module DailyRecordHelper
end

app/helpers/memo_helper.rb
module MemoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
<p><%= f.label :title, 'Title:' %><br>
<%= f.text_field :title %></br>
</p>
<p>
<%= f.label :content, 'Content:' %><br>
<%= f.text_area :content, size: "60x12" %></br>
</p>
<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %><br>
<%= f.submit %><br>
<% end %>


<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/articles/about.html.erb
<p class="container" style="margin-top: 100px;">
First rails practice project, a simple blog with basic functions.
</p>

app/views/articles/edit.html.erb
<% provide(:title, @article.title) %>
<div class="container" style="margin-top: 100px;"><h2>Edit Article</h2>

<div><% if @article.errors.any? %>
       <% @article.errors.full_messages.each do |e| %>
         <%= e %>
       <% end %>
     <% end %></div>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<% provide(:title, 'Index') %>
<div class="container" style="margin-top: 100px;"><h2>My Blog</h2>

<p><% if logged_in? %>
   <%= link_to 'New article', new_article_path %>
   <% end %></p>

<% @articles.each do |article| %>
<div class = "container" style="margin-top: 30px; border-style: solid; border-width: thin;"><strong><%= link_to article.title, article_path(article) %></strong> 
<%= article.created_at.to_s(:long) %></br>
<%= image_tag article.picture.url if article.picture? %>
<%= simple_format(article.content) %>
</div>
<% end %>
</div>

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<div class="container" style="margin-top: 100px;"><h2>New Article</h2>

<div><% if @article.errors.any? %>
       <% @article.errors.full_messages.each do |e| %>
         <%= e %>
       <% end %>
     <% end %></div>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<div class="container" style="margin-top: 100px;"><h2><%= @article.title %></h2>

<p><%= simple_format(@article.content) %></p><br>
<%= image_tag @article.picture.url if @article.picture? %><br>
<% if logged_in? %>
<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Delete', article_path(@article), method: :DELETE %>
<% end %>
<%= link_to 'Back', articles_path %>
</div>
<div class="container" style="margin-top: 100px;">
    
    <%= form_for([@article, @article.comments.build]) do |a| %>
    <%= a.label :content, 'Add comment' %>
    <%= a.text_field :content %>
    <%= a.submit 'send' %>
    <% end %>
    
    <p>Comments:</p>
    
    <ul>
    <% @article.comments.each do |c| %>
        <% if c.id != nil %>
        <li>
        <%= c.content %> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp at          
        <%= c.created_at.to_s(:short) %>
        <% if logged_in? %>
        <%= link_to 'delete', [c.article, c], method: :delete %>
        <% end %>
        </li>
        <% end %>
    <% end %>
    </ul>
</div>

app/views/daily_record/_form.html.erb
<table align="left", width="12%">
      <colgroup>
        <col span="1">
      </colgroup>
      
      <tr>
        <th><%= (@base_date + date_incre.day).to_date %> </th>
      </tr>
      <%= form_for date do |f| %>
      <%= f.hidden_field :base_date, value: @base_date + date_incre.day %> 
      <tr>
        <td><%= f.text_field :sleep_time %></td>
      </tr>
      <tr>
        <td>
          <%= f.number_field :restfulness %>
          </td>
      </tr>
      <tr>
        <td><%= f.text_area :study_progress, size: "24x12" %></td>
      </tr>
      <tr>
        <td><%= f.submit 'submit', class: 'myButton' %></td>
      </tr>
      <% end %>
    </table>

app/views/daily_record/daily_record.html.erb
<% provide(:title, 'Daily Records') %>
<head><div id="memo" style="margin: auto; width: 70%;">
  <%= form_for @memo do |f| %>
  <%= f.text_area :text, size: "160x15" %>
  <%= f.submit "save", class: 'myButton' %>
  <% end %>
  </div></head>
  <br>
<body>
  <div id="daily_record">
    <!-- Table 1 -->
    <table align="left", width="20%">
      <colgroup>
        <col span="7">
      </colgroup>
      <tr>
        <th>Date:</th>
        <th><%= @base_date.to_date %></th>
      </tr>
      <%= form_for @day1 do |f| %>
      <%= f.hidden_field :base_date, value: @base_date %>
      <tr>
        <td>Sleep Time:</td>
        <td><%= f.text_field :sleep_time %></td>
      </tr>
      <tr>
        <td>Restfulness:</td>
        <td>
          <%= f.number_field :restfulness %>
          </td>
      </tr>
      <tr>
        <td>Study Progress:</td>
        <td><%= f.text_area :study_progress, size: "24x12" %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit 'submit', class: 'myButton' %></td>
      </tr>
      <% end %>
    </table>
    
    <!--Table 2-->
    <%= render partial: 'form', locals: { date_incre: 1, date: @day2 } %>
    
    <!--Table 3-->
    <%= render partial: 'form', locals: { date_incre: 2, date: @day3 } %>
    
    <!--Table 4-->
    <%= render partial: 'form', locals: { date_incre: 3, date: @day4 } %>
    
    <!--Table 5-->
    <%= render partial: 'form', locals: { date_incre: 4, date: @day5 } %>
    
    <!--Table 6-->
    <%= render partial: 'form', locals: { date_incre: 5, date: @day6 } %>
    
    <!--Table 7-->
    <%= render partial: 'form', locals: { date_incre: 6, date: @day7 } %>
    
  </div>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
  <div align="center">
    <p><%= button_to 'Previous', daily_record_previous_path, method: :post, class: 'myButton' %></p>
    <p><%= button_to 'Next', daily_record_next_path, method: :post, class: 'myButton' %></p>
  </div>
  
</body>

send all records to:
<%= form_tag daily_record_send_mail_path do |f| %>
<%= text_field_tag :email %>
<%= submit_tag 'send' %>
<% end %>

app/views/layouts/_footer.html.erb
<p class="container" style="margin-top: 200px;">My first rails app for practice.</p>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-center">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'About', about_path %></li>
        <% if logged_in? %>
        <li><%= link_to 'Daily Record', daily_record_path %></li>
        <li><%= link_to 'Log out', logout_path, method: "delete" %></li>
        <li style="color: white;"><%= current_user.name %></li>
        <% else %>
        <li><%= link_to 'Sign up', signup_path %></li>
        <li><%= link_to 'Log in', login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<p class="container" style="margin-top: 40px;"><% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
<% end -%>
</p>
<%= yield %>

<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/users/new.html.erb
<div class="container">
<h1>Sign Up</h1>


  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |e| %>
      <%= e %><br>
    <% end %>
  <% end %>
</div>

<div class="container">
  <p><%= form_for @user do |f| %>
     <%= f.label :name %><br>
     <%= f.text_field :name, class: "form-control" %><br>
     <%= f.label :password %><br>
     <%= f.password_field :password, class: "form-control" %><br>
     <%= f.label :password_confirmation %><br>
     <%= f.password_field :password_confirmation, class: "form-control" %><br>
     <%= f.submit class: "btn btn-primary" %>
     <% end %>
  </p>
</div>